### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ericchan000**

### CODE REVIEW

**Comment by ericchan000** [comment]
zdfgvdzfv

**Comment by shufankang** [comment]
jdjal

**Comment by shufankang** [comment]
dhahdka

**Comment by ericchan000** [comment]
ojpoidfj

**Comment by ericchan000** [comment]
jhujhn

**Comment by ericchan000** [comment]
frsadf

**Comment by shufankang** [comment]
awdawd

**Comment by shufankang** [comment]
joijo

**Comment by ericchan000** [comment]
kjbjkb

**Comment by ericchan000** [comment]
jkhkjuh

**Comment by shufankang** [comment]
12312

**Comment by shufankang** [comment]
12311

**Comment by shufankang** [comment]
1231

**Comment by shufankang** [comment]
123

**Comment by ericchan000** [comment]
wrewf

**Comment by ericchan000** [comment]
What determines whether a GUI object will call my program when it's "action" happens?

**Comment by shufankang** [comment]
wo yi hui kan jian gaosu ni

**Comment by ericchan000** [comment]
hao

**Comment by ericchan000** [comment]
If I am shipping a program to customers (and thus don't want to ABEND) indicate which of my following methods should THROW (T) exceptions the compiler makes me handle and which should CATCH (C) them.

**Comment by ericchan000** [comment]
What determines whether a GUI object will call my program when it's "action" happens?

**Comment by ericchan000** [comment]
14. EXTRA CREDIT: In the ChatRoomServer, how could we tell when Bubba was joining if he was already in the chat room under another chat name?

**Comment by ericchan000** [comment]
17. Write a statement to declare an array called numbers that has three slots with the digits 7,8 and 9


是INT[]NUMBERS={7,8,9}
么？

**Comment by shufankang** [comment]
zuihou yi ge dui le 
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;

public class socket{
public static void main(String[] args) throws Exception 
   {

   Socket s = new Socket("10.139.65.24",1111);
   ObjectOutputStream oos = new ObjectOutputStream(s.getOutputStream());
   ObjectInputStream ois = new ObjectInputStream(s.getInputStream());
   oos.writeObject(args); 
   String[] reply = (String[]) ois.readObject(); 
   System.out.println(reply[0]+reply[1]+reply[2]); 
   s.close();
   }
}

**Comment by shufankang** [comment]
C. if I have given my program's address to the GUI object

**Comment by ericchan000** [comment]
2. If I am shipping a program to customers (and thus don't want to ABEND) indicate which of my following methods should THROW (T) exceptions the compiler makes me handle and which should CATCH (C) them.
 

   1. main() 
   2. constructor
   3. run()
   4. actionPerformed(ActionEvent ae)
   5. float add(String x, String y, String z)
   6. valueChanged(ListSelectionEvent lse)

**Comment by shufankang** [comment]
CCCTTT

**Comment by ericchan000** [comment]
14. EXTRA CREDIT: In the ChatRoomServer, how could we tell when Bubba was joining if he was already in the chat room under another chat name?
？

**Comment by shufankang** [comment]
Creat a HashMap<String,String> addressVsChatName
when some one join, 
check if(addressVsChatName.containKey(s.getAddress())) {some one is already in the chat room under another chat name; }
else{
addressVsChatName.put(s.getAddress(),chatName);
}
and delete while someone left

**Comment by ericchan000** [comment]
17. Write a statement to declare an array called numbers that has three slots with the digits 7,8 and 9
________________________________________________________________________________
WORD for 3 point
INT[]NUMBERS={7,8,9}

?

**Comment by ericchan000** [comment]
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import java.net.UnknownHostException;

public class Test {

	public static void main(String[] args) throws UnknownHostException, IOException, ClassNotFoundException
	{
		if(args.length != 3)
		{
			System.out.println("Error, enter 3 args!");
			return;
		}
		
		Socket s = new Socket("10.139.65.24",1111);
		ObjectOutputStream oos = new ObjectOutputStream(s.getOutputStream());
		
		oos.writeObject(args);
		ObjectInputStream ois = new ObjectInputStream(s.getInputStream());
		String[] quizanswer = (String[]) ois.readObject();
		System.out.println(quizanswer[1]+quizanswer[2]+quizanswer[3]);
		s.close();
	
		

	}

}

**Pull request merged**
